export const ProjectsData = [
  {
    id: 1,
    title: "Portfolio Website",
    desc: "Personal portfolio built with React, showcasing projects and skills.",
    challenges: "Integrating smooth animations, responsive design, and 3D effects.",
    team: ["Chandramohan"],
    screenshots: [
      "https://via.placeholder.com/300x200?text=Portfolio+1",
      "https://via.placeholder.com/300x200?text=Portfolio+2",
    ],
    github: "https://github.com/username/portfolio",
    tech: [
      { name: "React.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
      { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
      { name: "HTML", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
      { name: "CSS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
      { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg" },
    ],
  },
  {
    id: 2,
    title: "Rock Paper Scissors",
    desc: "A simple interactive game built using HTML, CSS, and JavaScript.",
    challenges: "Creating fair game logic and responsive UI.",
    team: ["1"],
    screenshots: ["/Screenshot 2025-08-17 154339.png","/Screenshot 2025-08-17 154355.png","/Screenshot 2025-08-17 154411.png","/Screenshot 2025-08-17 154431.png"],
    github: "https://github.com/chandramohan05/rock-paper-and-scissor",
    tech: [
      { name: "HTML", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
      { name: "CSS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
      { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
    ],
  },
  {
    id: 3,
    title: "To-Do List Application",
    desc: "A Spring Boot application to manage daily tasks with H2 Database.",
    challenges: "Implementing CRUD operations and integrating H2 database for persistence.",
    team: ["1"],
    screenshots: ["https://via.placeholder.com/300x200?text=ToDo+1"],
    github: "https://github.com/username/todo-app",
    tech: [
      { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
      { name: "Spring Boot", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg" },
      { name: "H2 Database", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/database/database-original.svg" },
    ],
  },
  {
    id: 4,
    title: "Student Management System",
    desc: "A Spring Boot + MySQL application for managing students and courses.",
    challenges: "Designing relational database structure and creating REST endpoints.",
    team: ["4"],
    screenshots: [
      "/Screenshot 2025-08-17 180825.png",
      "/Screenshot 2025-08-17 180740.png",
      "/Screenshot 2025-08-17 181139.png",
      "/Screenshot 2025-08-17 180936.png",
      "/Screenshot 2025-08-17 181059.png"
    ],
    github: "https://github.com/chandramohan05/STUDENT-DATA-MANAGEMENT-SYSTEM",
    tech: [
      { name: "HTML", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
      { name: "CSS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
      { name: "PHP", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg" },
      { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" },
    ],
  },
  {
    id: 5,
    title: "Book Store API",
    desc: "Spring Boot REST API for managing books, deployed on AWS with Docker.",
    challenges: "Implementing REST endpoints, Dockerizing the app, and deploying on AWS.",
    team: ["1"],
    screenshots: ["https://via.placeholder.com/300x200?text=BookStore+API"],
    github: "https://github.com/chandramohan05/BookStore",
    tech: [
      { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
      { name: "Spring Boot", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg" },
      { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" },
      { name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg" },
      { name: "AWS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg" },
    ],
  },
];
